language: python

python:
  - 2.6
  - "2.7_with_system_site_packages"

env:
  - PYTHONPATH=$PYTHONPATH:$PWD

virtualenv:
  system_site_packages: true

before_install:
 - sudo apt-get update
 - sudo apt-get install python-numpy python-opencv

install:
  - "pip install --pre -r requirements.txt"

script:
  - PYTHONPATH=`pwd` py.test