language: python

virtualenv:
  system_site_packages: true

before_install:
 - sudo apt-get update
 - sudo apt-get install python-numpy
install:
  - if [ ! -d "/tmp/opencv-2.4.9/build" ]; then cd /tmp && curl -L -O http://fossies.org/linux/misc/opencv-2.4.9.zip && unzip -o opencv-2.4.9.zip && cd opencv-2.4.9 && mkdir build && cd build && cmake -D WITH_TBB=ON -D BUILD_NEW_PYTHON_SUPPORT=ON -D WITH_V4L=ON -D INSTALL_C_EXAMPLES=ON -D INSTALL_PYTHON_EXAMPLES=ON -D BUILD_EXAMPLES=ON -D WITH_QT=ON -D WITH_OPENGL=ON .. && make && sudo make install; fi
  - cd $TRAVIS_BUILD_DIR
  - "pip install --pre -r requirements.txt"

python:
  - "2.7"

script:
  - PYTHONPATH=`pwd` py.test
